services:
  device-service:
    build: .
    container_name: device-service
    ports:
      - "8000:8000"
    # environment:
      # 可根据需要添加环境变量
      # - ENV_VAR=value
    volumes:
      - .:/app
    network_mode: "host"
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    #   interval: 30s
    #   timeout: 3s
    #   retries: 3
